# Generated by Django 4.2.4 on 2023-08-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_alter_blogdata_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authors",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="blogdata",
            name="title",
            field=models.CharField(max_length=60),
        ),
    ]
