# Generated by Django 4.2.3 on 2023-08-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_blogpost_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
